[pytest]
asyncio_mode = auto
testpaths = tests
filterwarnings =
    ignore:'crypt' is deprecated.*:DeprecationWarning:passlib\.utils
    ignore:datetime\.datetime\.utcfromtimestamp\(\) is deprecated.*:DeprecationWarning:pytz\.tzinfo
